print("enter 6 numbers")
x = input(), input(), input(), input(), input(), input()
d = (x)
print(type(d))
print("tuple of numbers")
print(d)
l = [x]
# l.sort()
print(type(l))
print("list")
print(l)
l.sort()
print("sorted list")
print(l)